name: data
on:
  schedule:
    - cron: 0 * * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
      - ./process_xlsx.js
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://www.pch.net/ixp/dir_data_csv
           downloaded_filename: data/countries_ixp.csv
           postprocess: ./process_csv.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://www.mobileconnectivityindex.com/widgets/connectivityIndex/excel/MCI_Data_2020.xlsx
           downloaded_filename: data/countries_mobile_connectivity.xlsx
           postprocess: ./process_xlsx.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://freedomhouse.org/sites/default/files/2020-10/FOTN_2020_Key_Internet_Controls_Updated.xlsx
           downloaded_filename: data/numger_key_internet_controls_employed.xlsx
           postprocess: ./process_xlsx.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://development-data-hub-s3-public.s3.amazonaws.com/ddhfiles/94586/wb_id4d_dataset_2018_0.xlsx
           downloaded_filename: data/id4d_nid.xlsx
           postprocess: ./process_xlsx.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://development-data-hub-s3-public.s3.amazonaws.com/ddhfiles/94586/wb_id4d_dataset_2018_0.xlsx
           downloaded_filename: data/id4d_legal.xlsx
           postprocess: ./process_xlsx.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://opencellid.org/ocid/downloads?token=pk.6f7a8f2cfa2bb43ea72428ed4a4b4f47&type=full&file=cell_towers.csv.gz
           downloaded_filename: data/cell_towers_geolocation.csv.gz
           postprocess: ./process_csv.gz.js
