name: data
on:
  schedule:
    - cron: 0 * * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
      - ./process_xlsx.js
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://www.pch.net/ixp/dir_data_csv
           downloaded_filename: data/countries_ixp.csv
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://www.mobileconnectivityindex.com/widgets/connectivityIndex/excel/MCI_Data_2020.xlsx
           downloaded_filename: data/countries_mobile_connectivity.xlsx
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://freedomhouse.org/sites/default/files/2020-10/FOTN_2020_Key_Internet_Controls_Updated.xlsx
           downloaded_filename: data/number_key_internet_controls_employed.xlsx
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://development-data-hub-s3-public.s3.amazonaws.com/ddhfiles/94586/wb_id4d_dataset_2018_0.xlsx
           downloaded_filename: data/id4d_nid.xlsx
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://development-data-hub-s3-public.s3.amazonaws.com/ddhfiles/94586/wb_id4d_dataset_2018_0.xlsx
           downloaded_filename: data/id4d_legal.xlsx
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://opencellid.org/ocid/downloads?token=pk.6f7a8f2cfa2bb43ea72428ed4a4b4f47&type=full&file=cell_towers.csv.gz
           downloaded_filename: data/cell_towers_geolocation.csv.gz
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://www.mobileconnectivityindex.com/widgets/connectivityIndex/excel/MCI_Data_2020.xlsx
           downloaded_filename: data/%_population_internet_coverage_2g.xlsx
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://www.mobileconnectivityindex.com/widgets/connectivityIndex/excel/MCI_Data_2021.xlsx
           downloaded_filename: data/%_population_internet_coverage_3g.xlsx
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://www.mobileconnectivityindex.com/widgets/connectivityIndex/excel/MCI_Data_2022.xlsx
           downloaded_filename: data/%_population_internet_coverage_4g.xlsx
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://www.mobileconnectivityindex.com/widgets/connectivityIndex/excel/MCI_Data_2023.xlsx
           downloaded_filename: data/%_population_internet_coverage_5g.xlsx
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://biogeo.ucdavis.edu/data/gadm3.6/gadm36_gpkg.zip
           downloaded_filename: data/gadm_database.zip
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://api.worldbank.org/v2/en/indicator/EG.ELC.ACCS.ZS?downloadformat=excel
           downloaded_filename: data/%_population_electricity_coverage.xls
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: http://www3.weforum.org/docs/WEF_GCI_4.0_2019_Dataset.xlsx
           downloaded_filename: data/elec_supply_quality.xlsx
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://data.humdata.org/dataset/5040df47-96a2-4b3c-9a7f-2b7fb2b41316/resource/f1143ea6-0349-423d-9aeb-7eb905f5ffc8/download/electrical_grid_cote_divoire_15.csv
           downloaded_filename: data/elec_dist_gride_maps.csv
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://www.mobileconnectivityindex.com/widgets/connectivityIndex/excel/MCI_Data_2020.xlsx
           downloaded_filename: data/spectrum_allocated_mobile_providers.csv
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://github.com/awslabs/open-data-registry/blob/main/datasets/speedtest-global-performance.yaml
           downloaded_filename: data/isp_speeds.yaml
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://www.itu.int/en/ITU-D/Statistics/Documents/statistics/2021/PercentIndividualsUsingInternet.xlsx
           downloaded_filename: data/%_individual_internet_usage.xlsx
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://www.itu.int/en/ITU-D/Statistics/Documents/statistics/2020/MobileCellularSubscriptions_2000-2019.xlsx
           downloaded_filename: data/%_mobile_cell_sub.xlsx
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://github.com/awslabs/open-data-registry/blob/main/datasets/speedtest-global-performance.yaml
           downloaded_filename: data/fixed_broadband_speed_download_upload_latency.yaml
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: http://pls.upu.int/pls/ap/layout.flexible_rpt3
           downloaded_filename: data/postal_coverage.txt
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://databank.worldbank.org/source/logistics-performance-index-(lpi)#
           downloaded_filename: data/countries_lpi.csv
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://docs.google.com/spreadsheets/d/1UC6AuwnX6xu8-fUc9KyActyNXXio6rIST6ga5CQFWLQ/view
           downloaded_filename: data/software_developer_ecosystem_size.xlsx
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://graph.linkedin.com/insights/labor-market#:~:text=ending%20April%202021-,Download%20data,-for%3A%20the%20Software
           downloaded_filename: data/digital_work_ecosystem_size.csv
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://development-data-hub-s3-public.s3.amazonaws.com/ddhfiles/1202896/public_use-talent-migration.xlsx
           downloaded_filename: data/migration_industry.xlsx
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://development-data-hub-s3-public.s3.amazonaws.com/ddhfiles/1202896/public_use-talent-migration.xlsx
           downloaded_filename: data/migration_skill.xlsx
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://development-data-hub-s3-public.s3.amazonaws.com/ddhfiles/1202896/public_use-talent-migration.xlsx
           downloaded_filename: data/migration_country.xlsx
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://stats.oecd.org/SDMX-JSON/data/PATS_COOP/EPO_A+PCT_A+USPTO_A.FOR_APP+FOR_APP_S+FOR_INV+FOR_INV_S+CO_INV+CO_INV_S.AUS+CAN+JPN+NLD+USA+EU27+EU28+WLD.TOTAL+WRD+JPN+USA+EU27+EU28.PRIORITY+APPLICATION/all?startTime=1999&endTime=2019&dimensionAtObservation=allDimensions&pid=0cb10255-1a67-42b2-a2f2-37ecfe3ebbd7
           downloaded_filename: data/international_co_inventions.json
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://unctad.org/system/files/information-document/DP.xlsx
           downloaded_filename: data/data_protect_privacy_legislation.xlsx
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://tcdata360-backend.worldbank.org/api/v1/datasets/53/dump.csv
           downloaded_filename: data/venture_cap_avail.csv
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://www.doingbusiness.org/content/dam/doingBusiness/excel/Historical-data---complete-data-with-scores.xlsx
           downloaded_filename: data/doing_bus_idx.xlsx
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://databank.worldbank.org/reports.aspx?source=2&series=IC.LGL.CRED.XQ#
           downloaded_filename: data/legal_rights_strength.csv
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://databank.worldbank.org/reports.aspx?source=2&series=IC.REG.DURS#
           downloaded_filename: data/time_start_bus.csv
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://databank.worldbank.org/reports.aspx?source=2&series=IC.BUS.EASE.XQ#
           downloaded_filename: data/ease_doing_bus.csv
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: http://hdr.undp.org/en/content/download-data
           downloaded_filename: data/%_population_using_internet.csv
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://stats.oecd.org/Index.aspx?DataSetCode=GIDDB2019
           downloaded_filename: data/%_population_using_internet_gender_index.csv
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://apiportal.uis.unesco.org/bdds
           downloaded_filename: data/sdg_data.csv
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: http://hdr.undp.org/en/content/download-data
           downloaded_filename: data/undp_human_developmnt.csv
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://data.humdata.org/dataset/e9988552-74e4-4ff4-943f-c782ac8bca87/resource/a9e327cc-d63f-4e61-b13d-d1968ee018bf/download/county_country_aug2020.tsv
           downloaded_filename: data/fb_social_connectedness.tsv
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://databank.worldbank.org/data/download/FINDEX_EXCEL.zip
           downloaded_filename: data/financial_inclusiveness.zip
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: http://api.worldbank.org/v2/en/indicator/IT.NET.USER.ZS?downloadformat=csv&source=2
           downloaded_filename: data/intenet_usage.zip
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://index.okfn.org/api/datasets.json
           downloaded_filename: data/open_data_idx.csv
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://www.mobileconnectivityindex.com/widgets/connectivityIndex/excel/MCI_Data_2020.xlsx
           downloaded_filename: data/gender_gap_in_mobile_usage.csv
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://www.mobileconnectivityindex.com/widgets/connectivityIndex/excel/MCI_Data_2020.xlsx
           downloaded_filename: data/tax_%_mobile_ownership.csv
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://globalfindex.worldbank.org/sites/globalfindex/files/2018-08/Global%20Findex%20Database.xlsx
           downloaded_filename: data/%_population_digital_financial_services.xlsx
           postprocess: ./process_raw_data.js

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
           http_url: https://unstats.un.org/unsd/demographic-social/products/worldswomen/annex_tables/List%20of%20countries%20-%20Table%209.xls
           downloaded_filename: data/list_of_countries.xlsx
           postprocess: ./process_raw_data.js
